# Generated by Django 4.2.6 on 2023-10-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
